version: "2.2"
services:
  anylog-query:
    image: anylogco/anylog-network:edgelake
    restart: always
    env_file:
      - anylog_query.env
    environment:
      - INIT_TYPE=prod
    container_name: anylog-query
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - anylog-query-anylog:/app/AnyLog-Network/anylog
      - anylog-query-blockchain:/app/AnyLog-Network/blockchain
      - anylog-query-data:/app/AnyLog-Network/data
      - anylog-query-local-scripts:/app/deployment-scripts
volumes:
  anylog-query-anylog:
  anylog-query-blockchain:
  anylog-query-data:
  anylog-query-local-scripts:
