version: "3"
services:
  anylog-${ANYLOG_TYPE}:
    image: anylogco/anylog-network:edgelake
    restart: always
    env_file:
      - anylog_${ANYLOG_TYPE}.env
    environment:
      - INIT_TYPE=prod
    container_name: anylog-${ANYLOG_TYPE}
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - anylog-${ANYLOG_TYPE}-anylog:/app/AnyLog-Network/anylog
      - anylog-${ANYLOG_TYPE}-blockchain:/app/AnyLog-Network/blockchain
      - anylog-${ANYLOG_TYPE}-data:/app/AnyLog-Network/data
      - anylog-${ANYLOG_TYPE}-local-scripts:/app/deployment-scripts
volumes:
  anylog-${ANYLOG_TYPE}-anylog:
  anylog-${ANYLOG_TYPE}-blockchain:
  anylog-${ANYLOG_TYPE}-data:
  anylog-${ANYLOG_TYPE}-local-scripts:
