services:
  edgelake-${EDGELAKE_TYPE}:
    image: ${DOCKER_IMAGE_BASE}:${DOCKER_IMAGE_VERSION}
    restart: always
    env_file:
      - edgelake_${EDGELAKE_TYPE}.env
    container_name: ${EDGELAKE_NODE_NAME}
    stdin_open: true
    tty: true
    network_mode: "host"
#    ports:
#      - ${ANYLOG_SERVER_PORT}:${ANYLOG_SERVER_PORT}
#      - ${ANYLOG_REST_PORT}:${ANYLOG_REST_PORT}
    volumes:
      - ${EDGELAKE_VOLUME}:/app/AnyLog-Network/anylog
      - ${BLOCKCHAIN_VOLUME}:/app/AnyLog-Network/blockchain
      - ${DATA_VOLUME}:/app/AnyLog-Network/data
      - ${LOCAL_SCRIPTS_VOLUME}:/app/deployment-scripts
volumes:
  ${EDGELAKE_VOLUME}:
  ${BLOCKCHAIN_VOLUME}:
  ${DATA_VOLUME}:
  ${LOCAL_SCRIPTS_VOLUME}:
